# Generated by Django 4.2.4 on 2023-08-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Topic title')),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Chapter title')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Task title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Task description')),
                ('target', models.TextField(blank=True, null=True, verbose_name='HTML Target')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(verbose_name='Task order')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.chapter')),
            ],
            options={
                'unique_together': {('chapter', 'order')},
            },
        ),
    ]
