# Generated by Django 4.2.4 on 2023-08-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Task order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('topic', 'order')},
        ),
    ]
