# Generated by Django 4.2.4 on 2023-08-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_chapter_order_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='rest_api.topic'),
        ),
    ]
