# Generated by Django 4.2.4 on 2023-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_alter_chapter_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='Topic order'),
        ),
    ]
