# Generated by Django 4.2.4 on 2023-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_topic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='long_description',
            field=models.TextField(default='This is a long description of a topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='short_description',
            field=models.TextField(default='this is a short description of a topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='this is a description', verbose_name='Task description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='target',
            field=models.TextField(default='<body>sample html placeholder</body>', verbose_name='HTML Target'),
            preserve_default=False,
        ),
    ]
