# Generated by Django 4.2.4 on 2023-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_topic_long_description_topic_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
