# Generated by Django 4.2.4 on 2023-08-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_topic_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='logo_url',
            field=models.URLField(default=1, verbose_name='Logo URL'),
            preserve_default=False,
        ),
    ]
