# Generated by Django 4.2.4 on 2023-09-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_alter_usertask_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='code',
            field=models.TextField(default='', verbose_name='Solution'),
            preserve_default=False,
        ),
    ]
