# Generated by Django 4.2.4 on 2023-09-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_rename_code_usertask_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='solution',
        ),
        migrations.AddField(
            model_name='usertask',
            name='css_code',
            field=models.TextField(default='', verbose_name='Solution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertask',
            name='html_code',
            field=models.TextField(default='', verbose_name='Solution'),
            preserve_default=False,
        ),
    ]
