# Generated by Django 4.2.4 on 2023-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_alter_usertask_css_code_alter_usertask_html_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='starter_code',
            field=models.TextField(blank=True, null=True, verbose_name='Starter code'),
        ),
    ]
