# Generated by Django 4.2.4 on 2023-09-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_task_starter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='starter_code',
        ),
        migrations.AddField(
            model_name='task',
            name='starter_css_code',
            field=models.TextField(blank=True, null=True, verbose_name='Starter CSS code'),
        ),
        migrations.AddField(
            model_name='task',
            name='starter_html_code',
            field=models.TextField(blank=True, null=True, verbose_name='Starter HTML code'),
        ),
    ]
