# Generated by Django 4.2.4 on 2023-10-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0019_remove_task_starter_code_task_starter_css_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=512)),
                ('challenges', models.TextField()),
                ('finishing_statement', models.TextField()),
            ],
        ),
    ]
