# Generated by Django 4.2.4 on 2023-10-30 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0020_topicdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdescription',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='rest_api.topic'),
            preserve_default=False,
        ),
    ]
