# Generated by Django 4.2.4 on 2023-10-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0022_alter_topicdescription_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='rest_api.topicdescription')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='rest_api.descriptionbody')),
            ],
        ),
    ]
