# Generated by Django 4.2.4 on 2023-10-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_descriptionbody_descriptionparagraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_learn', to='rest_api.topicdescription')),
            ],
        ),
        migrations.CreateModel(
            name='ToLearnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=256)),
                ('sub', models.CharField(max_length=1024)),
                ('topic_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_learn_item', to='rest_api.tolearn')),
            ],
        ),
    ]
