# Generated by Django 4.2.4 on 2023-10-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0024_tolearn_tolearnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicdescription',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicdescription',
            name='finishing_statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
