# Generated by Django 4.2.4 on 2023-10-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_alter_topicdescription_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionbody',
            name='topic_description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='rest_api.topicdescription'),
        ),
    ]
