# Generated by Django 4.2.4 on 2023-10-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0027_alter_descriptionbody_topic_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tolearnitem',
            old_name='topic_description',
            new_name='to_learn',
        ),
    ]
