# Generated by Django 4.2.4 on 2023-10-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0028_rename_topic_description_tolearnitem_to_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolearn',
            name='topic_description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_learn', to='rest_api.topicdescription'),
        ),
    ]
