import "./globals.css";
import type { Metadata } from "next";
import { Inter, Nunito, Raleway } from "next/font/google";

import Providers from "./providers";
import NavBar from "./components/NavBar";

export const inter = Inter({ subsets: ["latin"] });
export const raleway = Raleway({ subsets: ["latin"], display: "swap" });
export const nunito = Nunito({ subsets: ["latin"], display: "swap" });

// export const metadata: Metadata = {
//   title: "CSS Challenges",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
